feat(todo): Реализован туду лист согласно критериям
u1timaD/webbee-todo pull request #1
Opened 2024-06-21 06:19 UTC by u1timaD

2024-06-22 10:07 UTC, myaak requested changes
![image](https://github.com/u1timaD/webbee-todo/assets/113577353/0845f8fd-f522-4e25-ba2d-5119e15cd000)
Читабельности нет.

Вторая ошибка - у тебя если написать чето в Edit режиме и потом нажать Cancel и еще раз Edit, то останется то что я написал раньше.

2024-06-22 10:07 UTC, myaak commented on src/components/Button/Button.tsx
> +};
Очень странная кнопка, не вижу нереального кейса делать ее именно так. Можно сделать ее универсально как ui элемент. Но тогда с onClick нужно подумать

2024-06-22 10:07 UTC, myaak commented on src/components/Filter/Filter.tsx
> +const Filter = ({ handleChangeFilter }) => {
Вроде `tsx`, а типизации не вижу

2024-06-22 10:07 UTC, myaak commented on src/App.tsx
> +  };
Ты передаешь их вниз, нужно useCallback

2024-06-22 10:07 UTC, myaak commented on src/components/TaskEdit/TaskEdit.tsx
> +    ></input>
Тут можно одиночный селектор `<input />`
UPD: Не понимаю зачем вообще здесь нужен этот компонент. Перенасыщено

2024-06-22 10:07 UTC, myaak commented on src/App.tsx
> +                    key={idx}
У тебя массив изменяется, ключик как индекс использовать. Ай, ай,ай

2024-06-22 10:07 UTC, myaak commented on src/components/TaskItem/TaskItem.tsx
> +              }}
Все еще не понимаю смысла этой кнопки

2024-06-22 10:07 UTC, myaak commented on src/App.tsx
> +    setTasks([...tasks, newTask]);
Плохо так делать. А если я захочу добавить две подряд?

`
setTasks([...tasks, newTask]);
setTasks([...tasks, newTask]);
`
Что будет?)

2024-06-22 10:07 UTC, myaak commented on src/App.tsx
> +                )
Фильтры явно лучше вынести отсюда

2024-06-22 10:07 UTC, myaak commented on src/components/TaskItem/TaskItem.tsx
> +const TaskList = ({ task, index, handleClickDel, handleClickEdit }) => {
А типы где

2024-06-22 10:07 UTC, myaak commented on src/components/TaskItem/TaskItem.tsx
> +  const handleClickBtn = () => {
Ваще не понятно что функция делает из ее названия. Нажал на кнопку

2024-06-22 10:07 UTC, myaak commented on src/components/TaskItem/TaskItem.tsx
> +        )}
Почему раскидал все на разные компоненты, они же мелкие и без логики. Ничего особо не отделяешь

2024-07-01 11:38 UTC, IvanKoigerov commented on src/App.css
> +}
Вообще не круто что ты такие вещи вешаешь на все инпуты, с каким-то типом, потом если где-то понадобиться другой, человеку придется переделывать, так что делай компонент styled для этого

2024-07-01 11:38 UTC, IvanKoigerov commented on src/App.css
> +
В этом задании ты должен учиться использовать styled и mui, так что это все выноси от сюда

2024-07-01 11:38 UTC, IvanKoigerov commented on src/App.tsx
> +    { id: uuidv4(), name: 'Задача пятая: Подготовить презентацию для совещания в пятницу.' },
обычно такие вещи не пишут лишний раз в тело компонента, а выносят за него, чтобы не ухудшать читабельность

2024-07-01 11:38 UTC, IvanKoigerov commented on src/App.tsx
> +  }
типы тоже не пишут внутри компонента, выносим, лишняя информация просто

2024-07-01 11:38 UTC, IvanKoigerov commented on src/App.tsx
> +  };
Ты не по index удаляешь, а по id

2024-07-01 11:38 UTC, IvanKoigerov commented on src/App.tsx
> +  };
тут тоже

2024-07-01 11:38 UTC, IvanKoigerov commented on src/components/Button/Button.tsx
> +};
Ты как-то жестко не модифицируешь кнопку кроме стилей. В такой ситуации нет смысла создавать компонент, просто экспортируй стайлед

2024-07-01 11:38 UTC, IvanKoigerov commented on src/components/Button/Button.tsx
> +    props.cl === 'delete' || props.cl === 'cancel' ? '#D93D3D' : '#2d77af'};
такая себе тема, вообще не понятно что это значит по названию, надо использовать другое название.
Также ты в cl можешь передать любую стрингу, а тебе это не нужно, лучше всего ограничить определенными вариантами передачу данных

2024-07-01 11:38 UTC, IvanKoigerov commented on src/main.tsx
> +import './index.css';
Куча вещей которые тебе не нужны будто бы в этом index

2024-07-01 11:38 UTC, IvanKoigerov commented on src/components/TodoForm/TodoForm.tsx
> +        id=""
зачем передаешь, если не нужно?

2024-07-01 11:38 UTC, IvanKoigerov commented on src/components/TaskItem/TaskItem.tsx
> +            <Button name={'Edit'} handleClick={handleClickEdit} />
обычно если строку передаешь пропом то пишут так `prop="какой-то проп"`

2024-07-01 11:38 UTC, IvanKoigerov commented on src/components/TaskItem/TaskItem.tsx
> +  const [isChecked, setIsChecked] = useState(false);
не очень круто, если бы ты где-то использовал ещё тудухи, например ещё одна страница, там бы не было информации о том, что эта тудуха выполнена, соответсвенно не совсем корректное место хранения

2024-07-01 11:38 UTC, IvanKoigerov commented on src/components/TaskItem/TaskItem.tsx
> +const TaskList: React.FC<TaskListProps> = ({ task, index, number, clickDel, clickEdit }) => {
Сейчас никто не используют `React.FC<TaskListProps>` 
Почему? просто потому что он бесполезный

2024-07-01 11:38 UTC, IvanKoigerov commented on src/components/TaskItem/TaskItem.tsx
> +    clickDel(index);
Не очень хорошение название click что-то
Лучше всего использовать OnЧто-то потому что это значит при этом действии, по типу тех же onClick и OnSubmit

2024-07-01 11:38 UTC, IvanKoigerov commented on src/App.tsx
> +  };
Передаешь эти вещи куда-то, то нужно их обернуть в useCallback, во избежание лишних ререндеров у дочерних компонентов, вдруг там на эффект они завязаны. 

Всегда когда передаешь куда-то функции, то обязательно их оборачивать в useCallback

2024-07-01 11:38 UTC, IvanKoigerov commented on src/App.tsx
У тебя есть проблема

У тебя ререндеритья постоянно и поиск и форма создания, а такой ситуации не должно происходить

фильтр должен ререндериться лишь в тот момент когда ты пишешь в него, а также когда ты фильтруешь. Также когда ты вводишь значение в поиска, у тебя каждый введенный символ ререндерить компонент, а так не должно быть, тут нужно использовать дебаунс

Также у тебя ререндериться форма создания таски, когда фильтруешь или изменяешь таску, а это не круто, она должна ререндериться только когда ты ее используешь

![image](https://github.com/u1timaD/webbee-todo/assets/67396124/cb5208c0-cf0d-4479-8e6f-f73cc6df2272)

Ререндеры можешь пофиксить с помощью нескольких вещей, но советую юзать контекст
Отследить ререндеры можно с помощью консоль логов или реакт дев тулс

**Memo использовать нельзя**

2024-07-14 17:53 UTC, IvanKoigerov commented on src/components/TaskItem/TaskItem.tsx
> +  }, [setTasks, id, currentTask, task]);
если у тебя уже есть task то в map task может вызвать путаницу, лучше так не писать

2024-07-14 17:53 UTC, IvanKoigerov commented on src/components/TaskItem/TaskItem.tsx
> +  }, [setTasks, id, currentTask, task]);
ля сижу и не понимаю а task это что зачем тебе декомпзить до id его
Не совсем хорошое название переменной для текста task и currentTask, это не говорит из названия, что это текст, а не полноценная сущность

2024-07-14 17:53 UTC, IvanKoigerov commented on src/components/Todo/Todo.tsx
> +  );
у тебя при каждом ререндере компонента будет высчитываться значение, но всегда ли тебе это нужно? уверен ли ты в том что он будет выполняться только из-за изменений tasks и taskFilter

2024-07-14 17:53 UTC, IvanKoigerov commented on src/providers/FilterProvider.tsx
> +};
смотри сейчас у тебя будут ререндеры компонента, если он подписан на setTaskFilter, но ему не нужны значение этого фильтра, например кнопка очитки 
и она будет ререндериться, даже если setTaskFilter не изменился, но изменился taskFilter
А это не круто)

2024-07-14 17:53 UTC, IvanKoigerov commented on src/providers/TasksProvider.tsx
> +};
тоже что и с фильтром

2024-07-16 12:12 UTC, IvanKoigerov commented on src/providers/FilterProvider.tsx
> +  );
плохо сделал)) 
ты не должен закидывать в {}
У тебя в такой ситуации при каждом ререндере, все равно SetFilterContext будет новое значение возвращать, тк это {} и он создается при каждом ререндере

2024-07-16 12:12 UTC, IvanKoigerov commented on src/providers/TasksProvider.tsx
> +};
а вот тут норм, ноо tasks тоже без обьекта передавай

2024-07-16 12:24 UTC, merged